### ISSUE TITLE
Error: appspec.yml was not located at: ./

### ISSUE THREAD

**Issue by henriqueleite42** [sourcetoad/aws-codedeploy-action#93]
`appspec.yml` is not found, but it exists.

Repo:
https://github.com/econominhas/backend

GithubAction:
https://github.com/econominhas/backend/blob/master/.github/workflows/api-deploy.yml

Usage:
```yml
- name: AWS CodeBuild & CodeDeploy
  uses: sourcetoad/aws-codedeploy-action@v1
  with:
    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws_region: ${{ secrets.AWS_REGION }}
    codedeploy_name: Econominhas
    codedeploy_group: development_gropup
    s3_bucket: econominhas-dev-api-deploy
    s3_folder: api
    excluded_files: '.git/* .github/* .husky/* .vscode/* localstack/* openapi/* .dockerignore .editorconfig .eslintrc.js .gitignore .lintstagedrc .nvmrc .prettierrc docker-compose.yml Dockerfile.dev jest.config.json LICENSE README.md redocly.yaml'
    max_polling_iterations: 60
```

Pipe:
https://github.com/econominhas/backend/actions/runs/7427009109/job/20211875467
